#!/usr/bin/env sh
# Cut a release of this skills registry.
#
# Steps performed (idempotent where possible):
#   1. read the current version from `git describe --tags` (vX.Y.Z-N-gHASH)
#   2. derive the next version from the most recent annotated tag:
#        - if the working tree is dirty: fail
#        - if there are commits since the tag: bump patch (v0.3.0 -> v0.3.1)
#        - else: the tag already points at HEAD, no-op
#   3. run ./scripts/validate.sh; abort on failure
#   4. ask for confirmation (unless --yes is passed)
#   5. create an annotated tag `v<version>` at HEAD
#   6. push the tag and the current branch to origin
#   7. print the new tag so the caller can paste it into the release notes
#
# The script does NOT bump any version file (this repo has no package.json
# or similar); the source of truth is the git tag. The README's
# "Latest Release" section must already be in sync with the tag — the
# script does not edit it.

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
fi

YES=""
if [ "${1:-}" = "--yes" ] || [ "${1:-}" = "-y" ]; then
    YES=1
fi

# 1. current state
if [ -n "$(git status --porcelain)" ]; then
    echo "FAIL: working tree is dirty; commit or stash first" >&2
    exit 1
fi

CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
HEAD_SHA=$(git rev-parse --short HEAD)
COMMITS_SINCE=$(git rev-list --count "${CURRENT_TAG}..HEAD")

echo "current tag : $CURRENT_TAG"
echo "HEAD        : $HEAD_SHA"
echo "commits since: $COMMITS_SINCE"

# 2. derive next version
case "$COMMITS_SINCE" in
    0)
        echo "HEAD is already tagged at $CURRENT_TAG; nothing to release"
        exit 0
        ;;
    *)
        # bump patch: vX.Y.Z -> vX.(Y).(Z+1)
        base=${CURRENT_TAG#v}
        major=$(echo "$base" | cut -d. -f1)
        minor=$(echo "$base" | cut -d. -f2)
        patch=$(echo "$base" | cut -d. -f3)
        next_patch=$((patch + 1))
        NEXT_TAG="v${major}.${minor}.${next_patch}"
        ;;
esac

# 3. validate
./scripts/validate.sh

# 4. confirm
echo
echo "about to tag $NEXT_TAG at $HEAD_SHA"
echo "  message: \"Release $NEXT_TAG (auto-generated; $COMMITS_SINCE commits since $CURRENT_TAG)\""
echo
if [ -z "$YES" ]; then
    printf "continue? [y/N] "
    read -r ans
    case "$ans" in
        y|Y|yes|YES) ;;
        *) echo "aborted"; exit 1 ;;
    esac
fi

# 5. tag
git tag -a "$NEXT_TAG" -m "Release $NEXT_TAG

Auto-generated by scripts/release.sh. $COMMITS_SINCE commits since
$CURRENT_TAG.

Edit this annotation before pushing if you want a hand-written release
note; re-run with --yes after editing."

# 6. push
git push origin HEAD
git push origin "$NEXT_TAG"

# 7. echo
echo
echo "released: $NEXT_TAG"
echo "  inspect: git show $NEXT_TAG"
echo "  browse: https://github.com/liyown/skills-registry/releases/tag/$NEXT_TAG"
